// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LintRequest struct {
	FileString           string   `protobuf:"bytes,1,opt,name=file_string,json=fileString,proto3" json:"file_string,omitempty"`
	SqfluffCfgPath       string   `protobuf:"bytes,2,opt,name=sqfluff_cfg_path,json=sqfluffCfgPath,proto3" json:"sqfluff_cfg_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LintRequest) Reset()         { *m = LintRequest{} }
func (m *LintRequest) String() string { return proto.CompactTextString(m) }
func (*LintRequest) ProtoMessage()    {}
func (*LintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *LintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LintRequest.Unmarshal(m, b)
}
func (m *LintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LintRequest.Marshal(b, m, deterministic)
}
func (m *LintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LintRequest.Merge(m, src)
}
func (m *LintRequest) XXX_Size() int {
	return xxx_messageInfo_LintRequest.Size(m)
}
func (m *LintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LintRequest proto.InternalMessageInfo

func (m *LintRequest) GetFileString() string {
	if m != nil {
		return m.FileString
	}
	return ""
}

func (m *LintRequest) GetSqfluffCfgPath() string {
	if m != nil {
		return m.SqfluffCfgPath
	}
	return ""
}

type LintResultItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Warning              bool     `protobuf:"varint,4,opt,name=warning,proto3" json:"warning,omitempty"`
	StartLineNo          int32    `protobuf:"varint,5,opt,name=start_line_no,json=startLineNo,proto3" json:"start_line_no,omitempty"`
	StartLinePos         int32    `protobuf:"varint,6,opt,name=start_line_pos,json=startLinePos,proto3" json:"start_line_pos,omitempty"`
	EndLineNo            int32    `protobuf:"varint,7,opt,name=end_line_no,json=endLineNo,proto3" json:"end_line_no,omitempty"`
	EndLinePos           int32    `protobuf:"varint,8,opt,name=end_line_pos,json=endLinePos,proto3" json:"end_line_pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LintResultItem) Reset()         { *m = LintResultItem{} }
func (m *LintResultItem) String() string { return proto.CompactTextString(m) }
func (*LintResultItem) ProtoMessage()    {}
func (*LintResultItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *LintResultItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LintResultItem.Unmarshal(m, b)
}
func (m *LintResultItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LintResultItem.Marshal(b, m, deterministic)
}
func (m *LintResultItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LintResultItem.Merge(m, src)
}
func (m *LintResultItem) XXX_Size() int {
	return xxx_messageInfo_LintResultItem.Size(m)
}
func (m *LintResultItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LintResultItem.DiscardUnknown(m)
}

var xxx_messageInfo_LintResultItem proto.InternalMessageInfo

func (m *LintResultItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LintResultItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LintResultItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LintResultItem) GetWarning() bool {
	if m != nil {
		return m.Warning
	}
	return false
}

func (m *LintResultItem) GetStartLineNo() int32 {
	if m != nil {
		return m.StartLineNo
	}
	return 0
}

func (m *LintResultItem) GetStartLinePos() int32 {
	if m != nil {
		return m.StartLinePos
	}
	return 0
}

func (m *LintResultItem) GetEndLineNo() int32 {
	if m != nil {
		return m.EndLineNo
	}
	return 0
}

func (m *LintResultItem) GetEndLinePos() int32 {
	if m != nil {
		return m.EndLinePos
	}
	return 0
}

type LintResult struct {
	Items                []*LintResultItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LintResult) Reset()         { *m = LintResult{} }
func (m *LintResult) String() string { return proto.CompactTextString(m) }
func (*LintResult) ProtoMessage()    {}
func (*LintResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *LintResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LintResult.Unmarshal(m, b)
}
func (m *LintResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LintResult.Marshal(b, m, deterministic)
}
func (m *LintResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LintResult.Merge(m, src)
}
func (m *LintResult) XXX_Size() int {
	return xxx_messageInfo_LintResult.Size(m)
}
func (m *LintResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LintResult.DiscardUnknown(m)
}

var xxx_messageInfo_LintResult proto.InternalMessageInfo

func (m *LintResult) GetItems() []*LintResultItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*LintRequest)(nil), "pb.LintRequest")
	proto.RegisterType((*LintResultItem)(nil), "pb.LintResultItem")
	proto.RegisterType((*LintResult)(nil), "pb.LintResult")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4b, 0x4f, 0xb3, 0x40,
	0x14, 0x86, 0x3f, 0x5a, 0x7a, 0x3b, 0xb4, 0x7c, 0xe6, 0xac, 0x88, 0x0b, 0x25, 0xc4, 0x05, 0x6e,
	0x30, 0xa9, 0x49, 0x7f, 0x80, 0xae, 0x4c, 0xaa, 0x69, 0xe8, 0xc6, 0xb8, 0x21, 0x5c, 0x0e, 0xed,
	0x24, 0x74, 0x66, 0xca, 0x4c, 0x35, 0xee, 0xfc, 0xe9, 0x86, 0x01, 0x7b, 0xd9, 0x1d, 0x5e, 0x9e,
	0xf3, 0x64, 0x72, 0x5e, 0x98, 0x29, 0xaa, 0x3f, 0x59, 0x4e, 0x91, 0xac, 0x85, 0x16, 0xd8, 0x93,
	0x59, 0xf0, 0x0e, 0xce, 0x92, 0x71, 0x1d, 0xd3, 0xfe, 0x40, 0x4a, 0xe3, 0x2d, 0x38, 0x25, 0xab,
	0x28, 0x51, 0xba, 0x66, 0x7c, 0xe3, 0x59, 0xbe, 0x15, 0x4e, 0x62, 0x68, 0xa2, 0xb5, 0x49, 0x30,
	0x84, 0x2b, 0xb5, 0x2f, 0xab, 0x43, 0x59, 0x26, 0x79, 0xb9, 0x49, 0x64, 0xaa, 0xb7, 0x5e, 0xcf,
	0x50, 0x6e, 0x97, 0x3f, 0x97, 0x9b, 0x55, 0xaa, 0xb7, 0xc1, 0x4f, 0x0f, 0xdc, 0x56, 0xad, 0x0e,
	0x95, 0x7e, 0xd1, 0xb4, 0x43, 0x04, 0x3b, 0x17, 0x05, 0x75, 0x5a, 0x33, 0xa3, 0x0f, 0x4e, 0x41,
	0x2a, 0xaf, 0x99, 0xd4, 0x4c, 0xf0, 0xce, 0x75, 0x1e, 0x35, 0x5b, 0x3c, 0xdd, 0x91, 0xd7, 0x6f,
	0xb7, 0x9a, 0x19, 0x3d, 0x18, 0x7d, 0xa5, 0x35, 0x6f, 0xde, 0x68, 0xfb, 0x56, 0x38, 0x8e, 0xff,
	0x3e, 0x31, 0x80, 0x99, 0xd2, 0x69, 0xad, 0x93, 0x8a, 0x71, 0x4a, 0xb8, 0xf0, 0x06, 0xbe, 0x15,
	0x0e, 0x62, 0xc7, 0x84, 0x4b, 0xc6, 0xe9, 0x4d, 0xe0, 0x1d, 0xb8, 0x67, 0x8c, 0x14, 0xca, 0x1b,
	0x1a, 0x68, 0x7a, 0x84, 0x56, 0x42, 0xe1, 0x0d, 0x38, 0xc4, 0x8b, 0xa3, 0x67, 0x64, 0x90, 0x09,
	0xf1, 0xa2, 0xb3, 0xf8, 0x30, 0x3d, 0xfe, 0x6f, 0x1c, 0x63, 0x03, 0x40, 0x07, 0xac, 0x84, 0x0a,
	0x16, 0x00, 0xa7, 0x0b, 0x60, 0x08, 0x03, 0xa6, 0x69, 0xa7, 0x3c, 0xcb, 0xef, 0x87, 0xce, 0x1c,
	0x23, 0x99, 0x45, 0x97, 0x07, 0x8a, 0x5b, 0x60, 0xbe, 0x80, 0xc9, 0xeb, 0xf7, 0xba, 0xed, 0x0a,
	0xef, 0xc1, 0x6e, 0x28, 0xfc, 0x7f, 0xe2, 0x4d, 0x57, 0xd7, 0xee, 0xa5, 0x20, 0xf8, 0xf7, 0x34,
	0xfc, 0xb0, 0xa3, 0x07, 0x99, 0x65, 0x43, 0xd3, 0xef, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x71, 0xf6, 0x12, 0x1a, 0xf0, 0x01, 0x00, 0x00,
}
