# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x02pb\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t22\n\tMyService\x12%\n\x08SayHello\x12\x0b.pb.Request\x1a\x0c.pb.ResponseB-Z+github.com/j-clemons/dbt-language-server/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/j-clemons/dbt-language-server/pb'
  _globals['_REQUEST']._serialized_start=21
  _globals['_REQUEST']._serialized_end=47
  _globals['_RESPONSE']._serialized_start=49
  _globals['_RESPONSE']._serialized_end=74
  _globals['_MYSERVICE']._serialized_start=76
  _globals['_MYSERVICE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
